name: Python Demo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        type: string
        required: true
        description: Repository to create

env:
  APP_DIR: python/demo1_create_repo
  DEMO_GITHUBAPP_PRIVATE_KEY: ${{ secrets.DEMO_GITHUBAPP_PRIVATE_KEY }}
  DEMO_GITHUBAPP_APPID: ${{ secrets.DEMO_GITHUBAPP_APPID }}
  DEMO_GITHUBAPP_INSTALLATIONID: ${{ secrets.DEMO_GITHUBAPP_INSTALLATIONID }}
  DEMO_GITHUB_REPO_NAME: ${{ github.event.inputs.repo_name }}
  DEMO_GITHUB_REPO_OWNER: ${{ github.event.repository.owner.login }}

jobs:
  create-repo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        cd ${{ env.APP_DIR }}
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Token
      id: generate_token
      run: |
        cd ${{ env.APP_DIR }}
        python3 githubapp_generate_token.py
        
    - name: Create repository
      env:
        DEMO_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        cd ${{ env.APP_DIR }}
        python3 create_repo.py
